#!/usr/bin/env python3
"""Generate src/keywords/data.rs from the pyDYNA kwd.json field database.

kwd.json (Ansys pyDYNA, codegen/kwd.json) maps each LS-DYNA keyword to a list
of cards, each card a list of fields with {name, type, width, position}. We emit
a compact `&'static` Rust table that the keyword registry converts into schemas.

Usage:
    python codegen/gen_keywords.py [path/to/kwd.json]

kwd.json is large (~19 MB) and not vendored; fetch it with:
    curl -sSL -o codegen/kwd.json \\
        https://raw.githubusercontent.com/ansys/pydyna/main/codegen/kwd.json
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_KWD = ROOT / "codegen" / "kwd.json"
OUT = ROOT / "src" / "keywords" / "data.rs"

# kwd.json field type -> our compact type tag.
TYPE_MAP = {
    "integer": "I",
    "real": "F",
    "string": "S",
    "real-integer": "F",  # can be either; float is a safe superset for parsing
}


def sanitize(name: str, position: int) -> str:
    """A non-empty column name. kwd.json has blanks and 'NOT USED' placeholders;
    unused/blank fields must still be kept (their widths set later offsets)."""
    n = name.strip()
    if not n:
        return f"f{position}"
    # Keep it readable; Rust column names are plain strings, not identifiers.
    return re.sub(r"\s+", "_", n)


def dedup(names):
    """Make names unique within a keyword so column lookup is unambiguous."""
    seen = {}
    out = []
    for n in names:
        if n in seen:
            seen[n] += 1
            out.append(f"{n}_{seen[n]}")
        else:
            seen[n] = 1
            out.append(n)
    return out


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    kwd_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_KWD
    if not kwd_path.exists():
        sys.exit(f"kwd.json not found at {kwd_path}. See this script's docstring to fetch it.")

    kwd = json.loads(kwd_path.read_text())
    keywords = sorted(kwd.keys())  # sorted so the registry can binary-search

    lines = []
    lines.append("// @generated by codegen/gen_keywords.py from pyDYNA kwd.json — do not edit.")
    lines.append("#![cfg_attr(rustfmt, rustfmt::skip)]")
    lines.append("use super::{Fld, Kw, T};")
    lines.append("")
    lines.append("pub static KEYWORDS: &[Kw] = &[")

    n_fields = 0
    n_cards = 0
    for name in keywords:
        cards = kwd[name]
        card_strs = []
        # names deduped across the whole keyword (all cards flattened)
        for card in cards:
            fields = card.get("fields", [])
            raw_names = [sanitize(f.get("name", ""), f.get("position", 0)) for f in fields]
            uniq = dedup(raw_names)
            parts = []
            for f, cn in zip(fields, uniq):
                t = TYPE_MAP.get(f.get("type"), "F")
                w = int(f.get("width", 0) or 0)
                parts.append(f'Fld{{n:"{esc(cn)}",t:T::{t},w:{w}}}')
                n_fields += 1
            card_strs.append("&[" + ",".join(parts) + "]")
            n_cards += 1
        cards_joined = ",".join(card_strs)
        lines.append(f'    Kw{{name:"{esc(name)}",cards:&[{cards_joined}]}},')

    lines.append("];")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}")
    print(f"  keywords: {len(keywords)}  cards: {n_cards}  fields: {n_fields}")


if __name__ == "__main__":
    main()
